### ISSUE TITLE
ERROR: preg_match() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by paras-malhotra** [Maatwebsite/Laravel-Nova-Excel#12]
Got this error while exporting one of our Nova resources to Excel through the action:

```
preg_match() expects parameter 2 to be string, array given at /home/insense/PHP_GIT/prj/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php:62)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'preg_match() ex...', '/home/insense/PHP_...', 62, Array)
#1 /home/insense/PHP_GIT/prj/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php(62): preg_match('/^[\\\\+\\\\-]?(\\\\d+\\\\....', Array)
#2 /home/insense/PHP_GIT/prj/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php(34): PhpOffice\\PhpSpreadsheet\\Cell\\DefaultValueBinder::dataTypeForValue(Array)
#3 /home/insense/PHP_GIT/prj/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php(184): PhpOffice\\PhpSpreadsheet\\Cell\\DefaultValueBinder->bindValue(Object(PhpOffice\\PhpSpreadsheet\\Cell\\Cell), Array)
#4 /home/insense/PHP_GIT/prj/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2508): PhpOffice\\PhpSpreadsheet\\Cell\\Cell->setValue(Array)
#5 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Sheet.php(208): PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet->fromArray(Array, NULL, 'A1', false)
#6 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Sheet.php(359): Maatwebsite\\Excel\\Sheet->append(Array, 'A1', false)
#7 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Sheet.php(178): Maatwebsite\\Excel\\Sheet->appendRow(Array, Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel))
#8 /home/insense/PHP_GIT/prj/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Maatwebsite\\Excel\\Sheet->Maatwebsite\\Excel\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#9 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Sheet.php(180): Illuminate\\Database\\Eloquent\\Builder->chunk(200, Object(Closure))
#10 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Sheet.php(117): Maatwebsite\\Excel\\Sheet->fromQuery(Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel), Object(PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet))
#11 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Writer.php(97): Maatwebsite\\Excel\\Sheet->export(Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel))
#12 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Excel.php(126): Maatwebsite\\Excel\\Writer->export(Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel), 'Xls')
#13 /home/insense/PHP_GIT/prj/vendor/maatwebsite/excel/src/Excel.php(80): Maatwebsite\\Excel\\Excel->export(Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel), 'campaigns.xls', 'Xls')
#14 /home/insense/PHP_GIT/prj/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Maatwebsite\\Excel\\Excel->download(Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel), 'campaigns.xls', 'Xls')
#15 /home/insense/PHP_GIT/prj/vendor/maatwebsite/laravel-nova-excel/src/Actions/DownloadExcel.php(23): Illuminate\\Support\\Facades\\Facade::__callStatic('download', Array)
#16 /home/insense/PHP_GIT/prj/vendor/maatwebsite/laravel-nova-excel/src/Actions/ExportToExcel.php(89): Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel->handle(Object(Laravel\\Nova\\Http\\Requests\\ActionRequest), Object(Maatwebsite\\LaravelNovaExcel\\Actions\\DownloadExcel))
#17 /home/insense/PHP_GIT/prj/nova/src/Http/Controllers/ActionController.php(38): Maatwebsite\\LaravelNovaExcel\\Actions\\ExportToExcel->handleRequest(Object(Laravel\\Nova\\Http\\Requests\\ActionRequest))
#18 [internal function]: Laravel\\Nova\\Http\\Controllers\\ActionController->store(Object(Laravel\\Nova\\Http\\Requests\\ActionRequest), 'campaigns')
#19 /home/insense/PHP_GIT/prj/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#20 /home/insense/PHP_GIT/prj/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
```

Digging deeper, we found that this issue is related to: https://github.com/Maatwebsite/Laravel-Excel/issues/873

On further analysis, we found that one of the attributes in the resource is an accessor that we include like so:

```
/**
* The accessors to append to the model's array form.
*
* @var array
*/
protected $appends = ['promo_modes'];

//@return array
public function getPromoModesAttribute()
{
    return $someArray;
}
```

Exporting a model with array accessors results in this error. Is there a workaround to say possibly exclude this field in the exported XLS/CSV?

**Comment by patrickbrouwers** [comment]
Check the customization docs: https://laravel-excel.maatwebsite.nl/nova/1.0/exports/customizations.html#exporting-only-certain-columns You can use only() e.g.

**Comment by paras-malhotra** [comment]
Thanks @patrickbrouwers! That fixes it!
